import Head from 'next/head';
import { useState } from 'react';
import Door from '../components/Door';
import Gift from '../components/Gift';
import DoorModel from '../models/door';

export default function Home() {
  const [p1, setP1] = useState(new DoorModel(1));

  return (
    <>
      <Head>
        <title>Monty Hall Game</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main style={{ display: 'flex' }}>
        <Door value={p1} onChange={(newDoor) => setP1(newDoor)} />

        {/* <Gift /> */}
      </main>
    </>
  );
}
