import Head from 'next/head';
import Door from '../components/Door';
import Gift from '../components/Gift';

export default function Home() {
  return (
    <>
      <Head>
        <title>Monty Hall Game</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main style={{ display: 'flex' }}>
        <Door />
        <Door selected />
        <Door />
        {/* <Gift /> */}
      </main>
    </>
  );
}
